#api call for listing employee details
###
GET http://127.0.0.1:8000/employees/
Accept: application/json

#api call for adding employee
###
POST http://127.0.0.1:8000/employees/
Content-Type: application/json

{
    "name":"hari",
    "department":"hr",
    "salary":75000,
    "location":"ekm",
    "email":"hari@gmail.com"
}

#api call for retrieving employee detail
###
GET http://127.0.0.1:8000/employees/2/
Accept: application/json

#api call for deleting employee
###
DELETE http://127.0.0.1:8000/employees/2/
Content-Type: application/json